---
- hosts: all
  vars_files: env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks: 
    - name: Copy host file to etc host
      copy:
        src: hosts
        dest: /etc/hosts
    
    - name: config /etc/resolv.conf
      lineinfile:
        path: /etc/resolve.conf
        line: nameserver 8.8.8.8

- hosts: storage-1
  become: true
  tasks:
    - name: install nfs server
      yum: 
        name: "{{ item }}"
        state: latest
      loop:
        - nfs-utils
    
    - name: create directory /kolla_nfs
      file:
        path: /kolla_nfs
        state: directory

    - name: config /etc/exports
      lineinfile:
        path: /etc/exports
        line: /kolla_nfs 10.1.0.0/16(rw,sync,no_root_squash)
    
    - name: start nfs server
      service:
        name: nfs-server
        state: enabled
        permanent: yes
        immediate: yes
        
      