---
- hosts: all
  vars_files: env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks: 
    - name: Copy host file to etc host
      copy:
        src: hosts
        dest: /etc/hosts
    
    - name: config /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: nameserver 8.8.8.8
      
    - name: Prepare storage nfs
      includes_tasks: storage_nfs.yml
      when: input_storage_plan == "nfs"

    - name: Prepare storage lvm
      includes_tasks: storage_lvm.yml
      when: input_storage_plan == "lvm"
        
      