---
- hosts: localhost
  vars_files: env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks: 
    - name: Operate snapshot snap1
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: no
        folder: /khanhchu
        name: "{{ item.name }}"
        state: "{{ input_state }}"
        snapshot_name: snap1
        description: after k8s-prepare
        
      loop: "{{ vms }}" 
      delegate_to: localhost
      register: deploy
      