---
- hosts: localhost
  vars_files: env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks: 
    - name: Create a snap1 snapshot 
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: no
        folder: /khanhchu
        name: "{{ item.name }}"
        state: remove_all
        
      loop: "{{ vms }}" 
      delegate_to: localhost
      register: deploy
      